var GAME_LEVELS = [
  ["x          x!x                                                  ",
   "x          x!x                                                  ",
   "xo         x!x                                                  ",
   "xx         x!x                                                  ",
   "x          x!x                                                  ",
   "x                                                               ",
   "x    |                                                          ",
   "x                                                               ",
   "x           p       fff                                         ",
   "x                           yyy      o                          ",
   "x   xxx                              f                          ",
   "x   xxx                                                         ",
   "xx                                        x                   xx",
   "x             ii                          x                   x ",
   "x        xxtttxx                          x                   x ",
   "x        x     x                         xx                   x ",
   "x        x     x                          x                   x ",
   "x        x     x                          x                   x ",
   "x        x     x                          x                  ox ",
   "xyx      x     x                         xx              x  xxx ",
   "xxx @    x     x              xx    x    xx      x          x   ",
   "xxxxxxxxxx     x       xxxxxxxxx         xx               p x   ",
   "               xx!!!!!!xxxxxxxxx!!!!!!!!!xx               xxx   ",
   "               xxxxxxxxx       x!!!!!!!!!xx!!!!!!!!!!!!!!!!!x   ",
   "                               x!!!!!!!!!xx!!!!!!!!!!!!!!!!!x   ",
   "                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                "],

  ["                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                    xx     xx                      ",
   "                                                                                   ",
   "                        o                               o                          ",
   "                        x                     fff       o       xxx                ",
   "                                                        o                          ",
   "                                                                                   ",
   "                                   xxxxx                o                          ",
   "              xx                                        o                          ",
   "                                                        o                          ",
   "                                             x                                  x  ",
   "                                                        o                       x  ",
   "                                                        o                   o   x  ",
   "    x                                x       v       x  o                   x   x  ",
   "    x              o   o   o         xxxxxxxxxxxxxxxxx                          x  ",
   "    x                                                x                          x  ",
   "    x        x  x  o   o   o  x   x                  x  o  xxxxxxxxxxxxxxxxxxxxxx  ",
   "    x        x  x             x   x                  x  h  x                       ",
   "    x  @     x  x             x!!!x                  x!!!!!x                       ",
   "xxxxxxxxxxiiix  xxxxxxiiixxxxxx!!!x            o     x!!!!!x                       ",
   "                              xxxxxx                 xxxxxxx                       ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                              xyx                                  ",
   "                                                                                   ",
   "                                                                                   ",
   "                                     xyx                                           ",
   "             xxxx                                                                  ",
   "             x                                                                     ",
   "             x              xyx                                                    ",
   "      xyx    x                                                                     ",
   "             x                                                                     ",
   "o            x     xyx                                                             ",
   "xy!!!!!!!!!!!x                                                                     ",
   "xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                       f                                         vx xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                iiiii xxxxx iiiii xxxxx iiiii xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x  o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       |  o  |            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                  yy          xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "         yyy                                          xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxxtttttttttxxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                 o                         ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       xxxxx       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o           o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                   =                 x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],

   [" x   x                           ",
    "  x x                     x x    ",
    "   x  xxx x x   x       x   xxxx ",
    "   x  x x x x    x  x  x  x x  x ",
    "   x  xxx xxx     xxxxx   x x  x ",
    "                                 ",
    "                @                ",
    "!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!"]
];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
